#!/usr/bin/env python3
"""Build the 7x7x3 diag_accint ResNet-bottleneck traffic table — the 7x7x3
analogue of traffics_dnn_6base/rn50_6b_ls*_diag_accint.txt.

Two pure node-relabellings (traffic graph, rates, windows all preserved), then a
linear load rescale:
  1. XY-DIAGONAL walk  (remap_table_diagonal.py logic) — breaks axis-alignment,
     gives path diversity.
  2. ACCUMULATOR RELOCATION — swap the two conv2 reduction sinks onto two
     well-separated 6-face INTERIOR nodes, exactly as the 6x6x3 accint did
     (4<->43, 40<->63 there).  conv2 sinks on 7x7x3 are original nodes 0 and 49.
  3. pir/por *= target_ls / 0.05   (base table is LOAD_SCALE=0.05; linear).

Interior nodes on 7x7x3 = x in 1..5, y in 1..5, z=1 (6 faces).  Targets chosen
central and well-separated: (2,2,1)=65 and (4,4,1)=81 (4 hops apart).

Usage: python3 make_7x7x3_accint.py TARGET_LS OUT.txt
Leaves all 6x6x3 assets untouched.
"""
import sys

DX, DY, DZ = 7, 7, 3
BASE = "traffics_dnn/resnet50_bottleneck3_xb128_7x7x3.txt"
BASE_LOAD = 0.05
CONV2_SINKS = [0, 49]                      # original node ids (placement.csv, role=accumulator, layer=conv2)
INTERIOR_TARGETS = [2 + 2*DX + 1*DX*DY,    # (2,2,1) = 65
                    4 + 4*DX + 1*DX*DY]    # (4,4,1) = 81


def diagonal_walk():
    return [(( (i + j) % DX) + j*DX + z*DX*DY)
            for j in range(DY) for i in range(DX) for z in range(DZ)]


def main(target_ls, out):
    head, rows = [], []
    for line in open(BASE):
        if line.startswith('%'):
            head.append(line.rstrip('\n'))
        elif line.strip():
            rows.append(line.split())

    used = sorted({int(r[0]) for r in rows} | {int(r[1]) for r in rows})
    order = sorted(used, key=lambda n: ((n // DX) % DY, n % DX, n // (DX*DY)))
    diag = dict(zip(order, diagonal_walk()))
    assert len(set(diag.values())) == len(diag), "diagonal remap not injective"

    # post-diagonal ids of the conv2 sinks, then swap each with an interior node
    a0, a1 = diag[CONV2_SINKS[0]], diag[CONV2_SINKS[1]]
    t0, t1 = INTERIOR_TARGETS
    for t in (t0, t1):
        x, y, z = t % DX, (t // DX) % DY, t // (DX*DY)
        assert 1 <= x <= DX-2 and 1 <= y <= DY-2 and 1 <= z <= DZ-2, f"target {t} not interior"
    assert len({a0, a1, t0, t1}) == 4, "sink/target collision"
    swap = {a0: t0, t0: a0, a1: t1, t1: a1}

    def relabel(n):
        return swap.get(diag[n], diag[n])

    scale = target_ls / BASE_LOAD
    out_rows = []
    for r in rows:
        s, d = relabel(int(r[0])), relabel(int(r[1]))
        assert s != d, f"relabel created self-traffic at {s}"
        pir = f"{float(r[2])*scale:.10f}"
        por = f"{float(r[3])*scale:.10f}"
        out_rows.append([str(s), str(d), pir, por] + r[4:])

    # invariants
    assert len(out_rows) == len(rows)
    assert sorted(r[4:] for r in out_rows) == sorted(r[4:] for r in rows), "windows changed"
    assert len({int(r[0]) for r in out_rows} | {int(r[1]) for r in out_rows}) == len(used), "node count changed"

    with open(out, 'w') as f:
        for h in head:
            if h.startswith('% LOAD_SCALE'):
                f.write(f"% LOAD_SCALE={target_ls}  (rescaled x{scale:.4f} from base 0.05)  t_period=38536\n")
                continue
            if h.startswith('% src dst'):
                f.write("% PLACEMENT: XY-DIAGONAL relabelling of the base table\n")
                f.write(f"% ACCUMULATOR RELOCATION: {a0}<->{t0}, {a1}<->{t1} (interior, 6 faces each)\n")
                f.write("%   generated by make_7x7x3_accint.py -- graph/rates(scaled)/windows preserved\n")
            f.write(h + "\n")
        for r in out_rows:
            f.write("%6s %5s %s\n" % (r[0], r[1], " ".join(r[2:])))

    print(f"{BASE} -> {out}")
    print(f"  ls={target_ls}  rows={len(out_rows)}  conv2 sinks {a0},{a1} -> interior {t0},{t1}")


if __name__ == '__main__':
    main(float(sys.argv[1]), sys.argv[2])
