#!/usr/bin/env python3
"""Re-place a generated block traffic table onto an XY-diagonal walk.

This is a NODE RELABELLING, not a converter change: the traffic graph, every
pir/por, every phase window and the total volume are untouched -- only which
physical node each tile sits on changes.  That isolates placement as the single
variable against the existing ls=0.022 runs.

The current placement puts each layer in a 3D box (CONFIGS[...]["boxes"] in
stage2_dnn_traffic.py), which lands the partial-sum reduction axis along a mesh
axis.  modified2 odd-even-balanced admits exactly one path for an axis-aligned
flow, so DP and bufferlevel are provably identical on 48% of the block's bytes.
The diagonal walk offsets each mesh row's x by its y, breaking that alignment.

Usage:  python3 remap_table_diagonal.py IN.txt OUT.txt [DIMX DIMY DIMZ]
        (dims default to 7 7 3)
"""
import sys

DX, DY, DZ = 7, 7, 3


def nid(x, y, z):
    return x + y * DX + z * DX * DY


def diagonal_walk():
    """x offset by y, Z innermost -- a bijection over all DX*DY*DZ nodes."""
    return [nid((i + j) % DX, j, z)
            for j in range(DY) for i in range(DX) for z in range(DZ)]


def main(src, dst):
    print(f"  mesh {DX}x{DY}x{DZ}")
    head, rows = [], []
    for line in open(src):
        if line.startswith('%'):
            head.append(line.rstrip('\n'))
        elif line.strip():
            rows.append(line.split())

    used = sorted({int(r[0]) for r in rows} | {int(r[1]) for r in rows})
    # allocation order of the current placement, as the router sees it: the
    # occupied nodes in (y, x, z) order -- the same order the walk enumerates.
    order = sorted(used, key=lambda n: ((n // DX) % DY, n % DX, n // (DX * DY)))
    remap = dict(zip(order, diagonal_walk()))

    assert len(set(remap.values())) == len(remap), "remap is not injective"
    assert all(0 <= v < DX * DY * DZ for v in remap.values()), "node id out of range"

    out = []
    for r in rows:
        s, d = remap[int(r[0])], remap[int(r[1])]
        assert s != d, f"relabelling created self-traffic at {s}"
        out.append([str(s), str(d)] + r[2:])

    # invariants: same row count, same multiset of rates, same windows
    assert len(out) == len(rows)
    assert sorted(r[2] for r in out) == sorted(r[2] for r in rows), "pir changed"
    assert sorted(r[4:] for r in out) == sorted(r[4:] for r in rows), "windows changed"

    with open(dst, 'w') as f:
        for h in head:
            if h.startswith('% src dst'):
                f.write("% PLACEMENT: XY-DIAGONAL relabelling of the above table\n")
                f.write("%   generated by remap_table_diagonal.py -- traffic graph,\n")
                f.write("%   rates and phase windows identical; only node ids differ.\n")
            f.write(h + "\n")
        for r in out:
            f.write("%6s %5s %s\n" % (r[0], r[1], " ".join(r[2:])))

    print(f"{src} -> {dst}")
    print(f"  rows {len(out)}   nodes used {len(used)}   remapped bijectively")


if __name__ == '__main__':
    if len(sys.argv) > 4:
        DX, DY, DZ = (int(a) for a in sys.argv[3:6])
    main(sys.argv[1], sys.argv[2])
