## Variable that points to SystemC installation path
## OSNOME
# SYSTEMC =/home/a9902402/systemc-2.2.0

## NORLAMIN
#SYSTEMC = ~/tools/systemc-2.3.3-install
#WSL
SYSTEMC = $(HOME)/tools/systemc-2.3.3-install

INCDIR = -I. -I.. -I$(SYSTEMC)/include
LIBDIR = -L. -L.. -L$(SYSTEMC)/lib-$(TARGET_ARCH)

LIBS   =  -lsystemc -lm $(EXTRA_LIBS)


## Binaries live at the repo root (one level up); sources and .o live here.
EXE    = ../$(MODULE)

.SUFFIXES: .cpp .o 

$(EXE): $(OBJS) $(SYSTEMC)/lib-$(TARGET_ARCH)/libsystemc.a 
	$(CC) $(CFLAGS) $(INCDIR) $(LIBDIR) -Wl,-rpath,$(SYSTEMC)/lib-$(TARGET_ARCH) -o $@ $(OBJS) $(LIBS) 2>&1 | c++filt
.cpp.o:
	$(CC) $(CFLAGS) $(INCDIR) -c $<

clean:
	rm -f $(OBJS) *~ $(EXE) core *~ *.o

depend: 
	makedepend $(SRCS) -Y -f Makefile.deps

include ./Makefile.deps
